version: '3'
            
networks:
  mynetwork:
    external: true
            
services:
  c_mariadb:
    image: mariadb:10
    container_name: c_mariadb
    restart: always
    environment:
      MARIADB_DATABASE: devise_db
      MARIADB_ROOT_PASSWORD: root
    networks:
      mynetwork:
        aliases:
          - c_mariadb
          - mysql_host
          - mariadb_host
    expose:
      - 3306
    ports:
      - '3306:3306'
      
# service c_demo dans autre fichier docker-compose complémentaire