version: '3'
            
networks:
  mynetwork:
    external: true
            
services:  
  c_demo:
    #build : ../../rep_avec_Dockerfile
    image: xyz/demo
    restart: always
    container_name: c_demo
    environment:
      SPRING_PROFILES_ACTIVE: mysql,reinit
      #SPRING_PROFILES_ACTIVE: h2,reinit
    ports:
      - '8282:8181'
    networks:
      mynetwork:
        aliases:
          - c_demo
          - demo_host